#!/bin/bash
# crappy-commit
# Copyright (C) 2015  Benjamin Lippincott
msg_loc=~/.crap_messages.txt

if [[ $1 == "" ]]; then
	msg=$(head -$((${RANDOM} % `wc -l < $msg_loc` + 1)) $msg_loc | tail -1)
	git add -A && git commit -m "$msg" && git push
fi

if [[ $1 == "hemorrhoid" ]]; then
	msg=$(head -$((${RANDOM} % `wc -l < $msg_loc` + 1)) $msg_loc | tail -1)
	git add -A && git commit -m "$msg" && git push -f
fi

if [[ $1 == "add" ]]; then
	add_to_file=$2
	echo $add_to_file >> $msg_loc
	echo "$add_to_file added to file"
fi

if [[ $1 == "update" ]]; then
	if [[hash curl 2>/dev/null]]; then
		wget -O ~/.crap_messages.txt https://crappy-commit-server.herokuapp.com/messages.txt
	else
		curl -o ~/.crap_messages.txt https://crappy-commit-server.herokuapp.com/messages.txt
	fi
fi
exit