#!/bin/bash
# crappy-commit
# Copyright (C) 2015  Benjamin Lippincott
msg_loc=~/crappy-commit/messages.txt

if [[ $1 == "" ]]; then
	msg=$(head -$((${RANDOM} % `wc -l < $msg_loc` + 1)) $msg_loc | tail -1)
	git add -A && git commit -m "$msg" && git push
fi

if [[ $1 == "add" ]]; then
	add_to_file=$2
	echo $add_to_file >> $msg_loc
	echo "$add_to_file added to file"
fi

if [[ $1 == "install" ]]; then
	curl -o ~/.crap_messages.txt https://raw.githubusercontent.com/obiwanakin/crappy-commit/master/messages.txt
fi